spring:
  data:
    mongodb:
      host: mongodb-recommendation
      port: 27017
      database: fitness_recommendation_db
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: admin
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    listener:
      simple:
        acknowledge-mode: auto      # Manual ACK for reliability
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000      # 2 seconds before first retry
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true      # ← must be true (default is true, but verify)
    register-with-eureka: true
  instance:
    prefer-ip-address: true

server:
  port: 8083

# Gemini API
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}