spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/fitness_user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}  # ← YE ADD KARO
server:
  port: 8084